### ISSUE TITLE
Can't initialize app with nodester app init

### ISSUE THREAD

**Issue by diegovar** [nodester/nodester#100]
I'm trying to create an app and initialize it, but I get the following errors:

diego@diego-Ubuntu:~/Node.js applications$ nodester app init testapp3
nodester info initializing git repo for testapp3 into folder testapp3
nodester info cloning the repo git clone ec2-user@nodester.com:/node/hosted_apps/diegovarese/1101-b5879aba91829465d4bb9d48d524758c.git testapp3
nodester info clone complete
nodester info writing app data to config

fs.js:221
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: EBADF, Bad file descriptor 'testapp3/.nodester.appconfig'
    at Object.openSync (fs.js:221:18)
    at Object.writeFileSync (fs.js:512:15)
    at Object.writeApp (/usr/local/lib/node/.npm/nodester-cli/0.2.12/package/lib/config.js:54:8)
    at /usr/local/lib/node/.npm/nodester-cli/0.2.12/package/lib/app.js:230:37
    at ChildProcess.exithandler (child_process.js:106:7)
    at ChildProcess.emit (events.js:67:17)
    at ChildProcess.onexit (child_process.js:192:12)

**Comment by chrismatthieu** [comment]
same issue as 101 - check that ticket for details.
