### ISSUE TITLE
ReferenceError: TropoWebAPI is not defined 

### ISSUE THREAD

**Issue by chrismatthieu** [nodester/nodester#103]
Tropo-WebAPI library runs on localhost but not on Nodester

Nodester npm install express tropo-webapi <= success

Here's the app that is deployed to http://tropodemo.nodester.com 
topher/1320-b5bfe76c4277500de3f398e64f0ed504.git:
https://gist.github.com/920563

when you call the app vis skype (+990009369991489717) it returns the following error in nodester app logs:

christoffe:tropodemo christoffe$ nodester app logs tropodemo
nodester info Showing logs for: tropodemo
Munging require paths..
Globallizing Buffer
Reading file...
Nodester wrapped script starting (27279) at  Thu, 14 Apr 2011 21:07:56 GMT
[ERROR] You asked to listen on port 8000 but nodester will use port 9473 instead..
ReferenceError: TropoWebAPI is not defined
    at Object.<anonymous> (server.js:24:2)
    at param (/.node_libraries/.npm/connect/1.3.0/package/lib/middleware/router.js:148:21)
    at pass (/.node_libraries/.npm/connect/1.3.0/package/lib/middleware/router.js:164:10)
    at Object.router [as handle](/.node_libraries/.npm/connect/1.3.0/package/lib/middleware/router.js:170:6)
    at next (/.node_libraries/.npm/connect/1.3.0/package/lib/http.js:204:15)
    at IncomingMessage.<anonymous> (/.node_libraries/.npm/connect/1.3.0/package/lib/middleware/bodyParser.js:73:9)
    at IncomingMessage.emit (events.js:61:17)
    at HTTPParser.onMessageComplete (http.js:132:23)
    at Socket.ondata (http.js:1001:22)
    at Socket._onReadable (net.js:675:27)ReferenceError: TropoWebAPI is not defined
    at Object.<anonymous> (server.js:24:2)
    at param (/.node_libraries/.npm/connect/1.3.0/package/lib/middleware/router.js:148:21)
    at pass (/.node_libraries/.npm/connect/1.3.0/package/lib/middleware/router.js:164:10)
    at Object.router [as handle](/.node_libraries/.npm/connect/1.3.0/package/lib/middleware/router.js:170:6)
    at next (/.node_libraries/.npm/connect/1.3.0/package/lib/http.js:204:15)
    at IncomingMessage.<anonymous> (/.node_libraries/.npm/connect/1.3.0/package/lib/middleware/bodyParser.js:73:9)
    at IncomingMessage.emit (events.js:61:17)
    at HTTPParser.onMessageComplete (http.js:132:23)
    at Socket.ondata (http.js:1001:22)
    at Socket._onReadable (net.js:675:27)

We are planning to run Tropo/Nodester demos at jsconf and nodeconf!

**Comment by chrismatthieu** [comment]
require('tropo-webapi') doesn't work but var tropoapi = require('tropo-webapi') does.  App works when require is assigned to a variable like this:

var tropoapi = require('tropo-webapi');
var express = require('express');
var app = express.createServer(); 
var sys = require('sys');

/**
- Required to process the HTTP body
- req.body has the Object while req.rawBody has the JSON string
  */
  app.configure(function(){
  app.use(express.bodyParser());
  });

app.get('/', function(req, res) {
    res.send('app must be called from tropo');
});

app.post('/', function(req, res){
    sys.puts('answering call');
    // Create a new instance of the TropoWebAPI object.
    var tropo = new tropoapi.TropoWebAPI();
    // Use the say method https://www.tropo.com/docs/webapi/say.htm
    tropo.say("Welcome to my Tropo Web API node demo.");

```
// Demonstrates how to use the base Tropo action classes.
var say = {"value":"Please leave a message."};
// var choices = new tropo.Choices("[5 DIGITS]");
var choices = {"terminator":"#"};
var transcription = {"id":"1234", "url":"mailto:chris@matthieu.us"}

//function(attempts, bargein, beep, choices, format, maxSilence, maxTime, method, minConfidence, name, required, say, timeout, transcription, url, password, username)
tropo.record(null, null, null, choices, null, 7, 60, null, null, "recording", null, say, 10, transcription, "http://web1.tunnlr.com:11053/audio/filename.mp3", null, null);


res.send(tropoapi.TropoJSON(tropo));
```

});

app.listen(8000);
// console.log('Server running on http://0.0.0.0:8000/')

**Comment by chrismatthieu** [comment]
I think that this issue is related to https://github.com/nodester/nodester/issues/80

**Comment by chrismatthieu** [comment]
tracking under issue 80
