### ISSUE TITLE
EBADF, Bad file descriptor 'race/.nodester.appconfig'

### ISSUE THREAD

**Issue by ghost** [nodester/nodester#105]
hilip@philip-desktop:~$ nodester app init race
nodester info initializing git repo for race into folder race
nodester info cloning the repo git clone ec2-user@nodester.com:/node/hosted_apps/philip/1350-ed48ca0f0fdeab666ff8e7d743a71691.git race
nodester info clone complete
nodester info writing app data to config

fs.js:221
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: EBADF, Bad file descriptor 'race/.nodester.appconfig'
    at Object.openSync (fs.js:221:18)
    at Object.writeFileSync (fs.js:483:15)
    at Object.writeApp (/home/philip/local/lib/node/.npm/nodester-cli/0.2.12/package/lib/config.js:54:8)
    at /home/philip/local/lib/node/.npm/nodester-cli/0.2.12/package/lib/app.js:230:37
    at ChildProcess.exithandler (child_process.js:106:7)
    at ChildProcess.emit (events.js:67:17)
    at ChildProcess.onexit (child_process.js:192:12)
philip@philip-desktop:~$

**Comment by chrismatthieu** [comment]
Do you by chance have a passphrase on your RSA key?  See https://github.com/nodester/nodester/issues/101
