### ISSUE TITLE
nodester will not run

### ISSUE THREAD

**Issue by danielb2** [nodester/nodester#119]
After install I get the error below.

```
npm info nodester-cli
npm info using npm@0.3.18
npm info using node@v0.4.7
{ name: 'nodester-cli',
  description: 'A CLI tool to allow interaction with the http://nodester.com/ platform.',
  'dist-tags': { latest: '0.2.12' },
...
[~]$ nodester

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module 'nodester-cli'
    at Function._resolveFilename (module.js:320:11)
    at Function._load (module.js:266:25)
    at require (module.js:348:19)
    at Object.<anonymous> (/Users/daniel/local/Darwin/lib/node/.npm/nodester-cli/0.2.12/package/bin/nodester.js:4:11)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at Array.<anonymous> (module.js:423:10)
    at EventEmitter._tickCallback (node.js:126:26)
```

**Comment by danielb2** [comment]
I had installed node with homebrew for osx. When installing node.js with macports, nodester just works fine. I also had issues with the express package with the homebrew installation. I suspect the problem is the homebrew installation, not nodester.

**Comment by chrismatthieu** [comment]
Thanks for the update!  I have Node.JS 0.4.7 and NPM 0.3.18 installed natively on OSX and Nodester-CLI runs fine.
