### ISSUE TITLE
Regular Expressions Not Working in Express

### ISSUE THREAD

**Issue by richardanaya** [nodester/nodester#122]
I get an error on the regular expression when running the following code in nodester, but it works fine locally:
# 

var express = require('express')

var app = express.createServer()

app.configure( 
    function() {
    app.use(express.static(__dirname + '/root'));
    }
);

app.get(/^.*$/, 
    function(req, res) {
    res.redirect('index.html');
    }
);
app.listen(9753)

**Comment by chrismatthieu** [comment]
What does your log say?

nodester app logs your_app_name

You may need to use the /etc directory. Nodester creates this directory in every app.

**Comment by richardanaya** [comment]
nodester app logs logo
nodester info Showing logs for: logo
Munging require paths..
Globallizing Buffer
Reading file...
Nodester wrapped script starting (18196) at  Mon, 02 May 2011 21:22:35 GMT
TypeError: Object /^._$/ has no method 'concat'
    at normalize (/.node_libraries/.npm/express/2.3.2/package/lib/router/route.js:49:6)
    at new Route (/.node_libraries/.npm/express/2.3.2/package/lib/router/route.js:27:17)
    at HTTPServer.<anonymous> (/.node_libraries/.npm/express/2.3.2/package/lib/router/index.js:87:19)
    at HTTPServer.get (/.node_libraries/.npm/express/2.3.2/package/lib/http.js:493:25)
    at server.js:11:5
    at /node/nodester/scripts/launch_chrooted_app.js:205:20
    at [object Object].<anonymous> (fs.js:107:5)
    at [object Object].emit (events.js:61:17)
    at afterRead (fs.js:878:12)
    at wrapper (fs.js:245:17){ stack: [Getter/Setter],
  arguments: [ 'concat', /^._$/ ],
  type: 'undefined_method',
  message: [Getter/Setter] }

**Comment by DanBUK** [comment]
For example https://gist.github.com/1070014 in a node shell does not create an object with a concat method. Therefore I don't think this is a nodester issue.
