### ISSUE TITLE
EADDRINUSE, Address already in use

### ISSUE THREAD

**Issue by azproduction** [nodester/nodester#128]
Full application conde cn be found at https://github.com/azproduction/javascript-ecdc/tree/master/examples/md5-bruteforce-server.js (application does not do anything evil - it's just an example of my framework) and all files in https://github.com/azproduction/javascript-ecdc/tree/master/examples/md5-bruteforce-server

nodester version is using `javascript-ecdc` as module
`server.js` simple requires bootstrap of `md5-bruteforce-server`:

```
require('./javascript-ecdc/examples/md5-bruteforce-server.js');
```

at http://ecdc.nodester.com/ ive:

```
The application is not running..
ECONNREFUSED, Connection refused
```

`$ nodester app logs ecdc`:

```
nodester info Showing logs for: ecdc
Munging require paths..
Globallizing Buffer
Reading file...
Nodester wrapped script starting (32506) at  Tue, 17 May 2011 09:04:04 GMT
Error: EADDRINUSE, Address already in use
    at HTTPServer._doListen (net.js:1098:5)
    at net.js:1069:14
    at Object.lookup (dns.js:153:45)
    at HTTPServer.listen (net.js:1063:20)
    at /javascript-ecdc/examples/md5-bruteforce-server.js:12:23
    at /javascript-ecdc/examples/md5-bruteforce-server/Md5BruteForceServer.js:273:21
    at Statement.<anonymous> (/.node_libraries/.npm/sqlite/1.0.4/package/sqlite.js:130:11){ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'EADDRINUSE, Address already in use',
  errno: 98,
  code: 'EADDRINUSE',
  syscall: 'bind' }
```

`$ nodester app start ecdc`:

```
nodester info Attemping to start app: ecdc
nodester info app started.
```

`$ nodester app info ecdc`:

```
nodester info Gathering information about: ecdc
nodester info ecdc on port 10046 running: true (pid: 32518)
nodester info gitrepo: ec2-user@nodester.com:/node/hosted_apps/azproduction/1893-...7b21d9.git
nodester info appfile: server.js
```

application uses `express`, `ejs`, `sqlite` (tiny db in `:memory:`)

**Comment by azproduction** [comment]
My issue solved. There was a bug with submodules update.
