### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL at /node/nodester/scripts/launch_chrooted_app.js:205:20

### ISSUE THREAD

**Issue by kbjr** [nodester/nodester#131]
I can't seem to start my app. After telling the app to start, the page just shows a connection refused error. After checking the logs i got this:

```
Munging require paths..
Globallizing Buffer
Reading file...
Nodester wrapped script starting (32093) at  Wed, 01 Jun 2011 01:01:48 GMT
SyntaxError: Unexpected token ILLEGAL
    at /node/nodester/scripts/launch_chrooted_app.js:205:20
    at [object Object].<anonymous> (fs.js:107:5)
    at [object Object].emit (events.js:61:17)
    at afterRead (fs.js:878:12)
    at wrapper (fs.js:245:17){ stack: [Getter/Setter],
  arguments: [ 'ILLEGAL' ],
  type: 'unexpected_token',
  message: [Getter/Setter] }
```

**Comment by kbjr** [comment]
nevermind, i figured it out...
