### ISSUE TITLE
Bad file descriptor when initializing new app

### ISSUE THREAD

**Issue by Gooseus** [nodester/nodester#139]
Tried to make my first app on nodester, heres' what I did:

[root@dev webnode]# nodester app init testapp420
nodester info initializing git repo for testapp420 into folder testapp420
nodester info cloning the repo git clone ec2-user@nodester.com:/node/hosted_apps/gooseus/2259-93f4f29fc69b7d81645471724e59783a.git testapp420
nodester info clone complete
nodester info writing app data to config

fs.js:221
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: EBADF, Bad file descriptor 'testapp420/.nodester.appconfig'
    at Object.openSync (fs.js:221:18)
    at Object.writeFileSync (fs.js:522:15)
    at Object.writeApp (/usr/local/lib/node_modules/nodester-cli/lib/config.js:54:8)
    at /usr/local/lib/node_modules/nodester-cli/lib/app.js:230:37
    at ChildProcess.exithandler (child_process.js:106:7)
    at ChildProcess.emit (events.js:67:17)
    at ChildProcess.onexit (child_process.js:192:12)

I had already created the app without any problems, is there something I'm missing?  I'm running on CentOS 5.5  and it looks like I have node v0.5.0-pre... I tried to roll back to v0.4.7 with an npm package called n, but it doesn't seem to have worked.  I can't tell if that's the problem or if there is something else I'm missing. 
- Shawn

**Comment by Gooseus** [comment]
alright, got n to roll it back, if it's to be trusted, I am now using version 0.47

[root@dev webnode]# node -v
v0.4.7
[root@dev webnode]# nodester app init testapp420
nodester info initializing git repo for testapp420 into folder testapp420
nodester info cloning the repo git clone ec2-user@nodester.com:/node/hosted_apps/gooseus/2259-93f4f29fc69b7d81645471724e59783a.git testapp420
nodester info clone complete
nodester info writing app data to config

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: EBADF, Bad file descriptor 'testapp420/.nodester.appconfig'
    at Object.openSync (fs.js:221:18)
    at Object.writeFileSync (fs.js:483:15)
    at Object.writeApp (/usr/local/lib/node_modules/nodester-cli/lib/config.js:54:8)
    at /usr/local/lib/node_modules/nodester-cli/lib/app.js:230:37
    at ChildProcess.exithandler (child_process.js:106:7)
    at ChildProcess.emit (events.js:67:17)
    at Socket.<anonymous> (child_process.js:172:12)
    at Socket.emit (events.js:64:17)
    at Array.<anonymous> (net.js:829:12)
    at EventEmitter._tickCallback (node.js:126:26)
[root@dev webnode]#

**Comment by Gooseus** [comment]
Nevermind, found answer on your tumblr blog:

http://nodester.tumblr.com/post/4472243958/passwords-and-passphrases-tips
