### ISSUE TITLE
nodester npm install <module> broken.

### ISSUE THREAD

**Issue by fschwehn** [nodester/nodester#154]
since yesterday any attempt to install a module would result in an terminal output like so:

~/nodester/svf$ nodester npm install connect
nodester info installing to app: svf
nodester info installing these npm packages: connect
nodester └── mime@1.2.2

/Users/fschwehn/local/node/lib/node_modules/nodester-cli/lib/npm.js:40
                            if (l[1].toLowerCase() === 'warn') {
                                     ^
TypeError: Cannot call method 'toLowerCase' of undefined
    at /Users/fschwehn/local/node/lib/node_modules/nodester-cli/lib/npm.js:40:38
    at Array.forEach (native)
    at /Users/fschwehn/local/node/lib/node_modules/nodester-cli/lib/npm.js:34:21
    at [object Object].callback (/Users/fschwehn/local/node/lib/node_modules/nodester-cli/node_modules/nodester-api/nodester.js:44:5)
    at [object Object].<anonymous> (/Users/fschwehn/local/node/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:273:21)
    at [object Object].emit (events.js:64:17)
    at IncomingMessage.<anonymous> (/Users/fschwehn/local/node/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:261:54)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at Socket.ondata (http.js:1221:22)

**Comment by DanBUK** [comment]
I pushed out a newer version of nodester-cli last week; can you please update you nodester-cli package and re-test as this should be fixed.

**Comment by abdulmueid** [comment]
Run the nodester npm install <module> from the project directory. Running it elsewhere will throw errors.

**Comment by fschwehn** [comment]
works like a charm now. thanks!
