### ISSUE TITLE
nodester npm install not working

### ISSUE THREAD

**Issue by yyx990803** [nodester/nodester#174]
Error shown:

/Users/Evan/local/node/lib/node_modules/nodester-cli/lib/npm.js:40
                            if (l[1].toLowerCase() === 'warn') {
                                     ^
TypeError: Cannot call method 'toLowerCase' of undefined
    at /Users/Evan/local/node/lib/node_modules/nodester-cli/lib/npm.js:40:38
    at Array.forEach (native)
    at /Users/Evan/local/node/lib/node_modules/nodester-cli/lib/npm.js:34:21
    at [object Object].callback (/Users/Evan/local/node/lib/node_modules/nodester-cli/node_modules/nodester-api/nodester.js:44:5)
    at IncomingMessage.<anonymous> (/Users/Evan/local/node/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:260:21)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at Socket.ondata (http.js:1226:22)
    at Socket._onReadable (net.js:683:27)
    at IOWatcher.onReadable [as callback](net.js:177:10)

**Comment by yocontra** [comment]
Update nodester-cli, this issue was fixed with https://github.com/nodester/nodester-cli/commit/1ed04d72db68e340a3dd8faeeb28c43c82988613
