### ISSUE TITLE
NowJS/Socket.IO issue

### ISSUE THREAD

**Issue by mitchbox** [nodester/nodester#181]
I have followed the #168 issue to setup my app,
but it still shows the following error:
An error has occurred: {"stack":"Error: ECONNREFUSED, Connection refused\n    at Socket._onConnect (net.js:601:18)\n    at IOWatcher.onWritable [as callback](net.js:186:12)","message":"ECONNREFUSED, Connection refused","errno":111,"code":"ECONNREFUSED","syscall":"connect"}

My server.js as followed:
var http = require('http');
var sys = require('sys');
var io = require('socket.io');
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello World\nApp (myapps) is running..');
}).listen(process.env["app_port"]);

And "nodester npm list app_name" shows the following:
nodester ├─┬ express@2.4.3 
nodester │ ├── connect@1.6.0 
nodester │ ├── mime@1.2.2 
nodester │ └── qs@0.3.0 
nodester ├── jade@0.13.0 
nodester └─┬ now@0.7.0 
nodester   ├── node-proxy@0.4.0 
nodester   └─┬ socket.io@0.7.7 
nodester     ├── policyfile@0.0.3 
nodester     └─┬ socket.io-client@0.7.4 
nodester       └── uglify-js@1.0.3

logs as followed:
New PID: 54443
chroot_runner
chroot_runner

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
^
Error: Cannot find module 'socket.io'
    at Function._resolveFilename (module.js:317:11)
    at Function._load (module.js:262:25)
    at require (module.js:346:19)
    at Object.<anonymous> (/app/server.js:3:10)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at Array.<anonymous> (module.js:421:10)
    at EventEmitter._tickCallback (node.js:126:26)

Process died with exit code 1. Restarting...

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
^
Error: Cannot find module 'socket.io'
    at Function._resolveFilename (module.js:317:11)
    at Function._load (module.js:262:25)
    at require (module.js:346:19)
    at Object.<anonymous> (/app/server.js:3:10)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at Array.<anonymous> (module.js:421:10)
    at EventEmitter._tickCallback (node.js:126:26)

Process died with exit code 1. Restarting...

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
^
Error: Cannot find module 'socket.io'
    at Function._resolveFilename (module.js:317:11)
    at Function._load (module.js:262:25)
    at require (module.js:346:19)
    at Object.<anonymous> (/app/server.js:3:10)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at Array.<anonymous> (module.js:421:10)
    at EventEmitter._tickCallback (node.js:126:26)

Process died with exit code 1. Restarting...

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
^
Error: Cannot find module 'socket.io'
    at Function._resolveFilename (module.js:317:11)
    at Function._load (module.js:262:25)
    at require (module.js:346:19)
    at Object.<anonymous> (/app/server.js:3:10)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at Array.<anonymous> (module.js:421:10)
    at EventEmitter._tickCallback (node.js:126:26)

Process died with exit code 1. Restarting...

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
^
Error: Cannot find module 'socket.io'
    at Function._resolveFilename (module.js:317:11)
    at Function._load (module.js:262:25)
    at require (module.js:346:19)
    at Object.<anonymous> (/app/server.js:3:10)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at Array.<anonymous> (module.js:421:10)
    at EventEmitter._tickCallback (node.js:126:26)

Process died with exit code 1. Restarting...

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
^
Error: Cannot find module 'socket.io'
    at Function._resolveFilename (module.js:317:11)
    at Function._load (module.js:262:25)
    at require (module.js:346:19)
    at Object.<anonymous> (/app/server.js:3:10)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at Array.<anonymous> (module.js:421:10)
    at EventEmitter._tickCallback (node.js:126:26)

Error: Restarted too many times, bailing.

While I remove "var io = require('socket.io');", and it works well.
Please help me to resolve this problem, thanks.

**Comment by yocontra** [comment]
Can you try uninstalling and installing socket.io again via `nodester npm`?

**Comment by mitchbox** [comment]
Hi Contra,
I have uninstalling and installing socket.io again via nodester npm,
and it still not works well.
But I try to restart my app again and again, then it works well!!
Anyway, thanks for you help!!

**Comment by yocontra** [comment]
When you run an npm install make sure you follow all of the instructions before reporting it as an issue! I believe it explicitly says to restart your app at the end.
