### ISSUE TITLE
Dependencies not being installed to sandbox

### ISSUE THREAD

**Issue by eflorico** [nodester/nodester#191]
I am unable to install the libxmljs package on Nodester. The reason for this seems to be that SCons is not installed on the server:

```
Eric-Wolfs-MacBook-Pro:updatified ewolf$ nodester npm install libxmljs
nodester info installing to app: updatified
nodester info installing these npm packages: libxmljs
nodester > libxmljs@0.4.2 preuninstall /node/app/ewolf/3394-96259eb266ae50df8727f64cbd8a64a1_rw/node_modules/libxmljs
nodester > make clean
nodester > libxmljs@0.4.2 preuninstall /node/app/ewolf/3394-96259eb266ae50df8727f64cbd8a64a1_rw/node_modules/libxmljs
nodester > make clean
nodester make: scons: Command not found
nodester make: *** [clean] Error 127
nodester npm ERR! error installing libxmljs@0.4.2 Error: libxmljs@0.4.2 preuninstall: `make clean`
nodester npm ERR! error installing libxmljs@0.4.2 `sh "-c" "make clean"` failed with 2
nodester npm ERR! error installing libxmljs@0.4.2     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
nodester npm ERR! error installing libxmljs@0.4.2     at ChildProcess.emit (events.js:67:17)
nodester npm ERR! error installing libxmljs@0.4.2     at ChildProcess.onexit (child_process.js:192:12)
nodester make: scons: Command not found
nodester make: *** [clean] Error 127
nodester npm ERR! error rolling back libxmljs@0.4.2 Error: libxmljs@0.4.2 preuninstall: `make clean`
nodester npm ERR! error rolling back libxmljs@0.4.2 `sh "-c" "make clean"` failed with 2
nodester npm ERR! error rolling back libxmljs@0.4.2     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
nodester npm ERR! error rolling back libxmljs@0.4.2     at ChildProcess.emit (events.js:67:17)
nodester npm ERR! error rolling back libxmljs@0.4.2     at ChildProcess.onexit (child_process.js:192:12)
nodester npm ERR! libxmljs@0.4.2 preuninstall: `make clean`
nodester npm ERR! `sh "-c" "make clean"` failed with 2
nodester npm ERR! 
nodester npm ERR! Failed at the libxmljs@0.4.2 preuninstall script.
nodester npm ERR! This is most likely a problem with the libxmljs package,
nodester npm ERR! not with npm itself.
nodester npm ERR! Tell the author that this fails on your system:
nodester npm ERR!     make clean
nodester npm ERR! You can get their info via:
nodester npm ERR!     npm owner ls libxmljs
nodester npm ERR! There is likely additional logging output above.
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.11-83.9.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "libxmljs"
nodester npm ERR! cwd /node/app/ewolf/3394-96259eb266ae50df8727f64cbd8a64a1_rw
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.18
nodester npm ERR! 
nodester npm ERR! Additional logging details can be found in:
nodester npm ERR!     /node/app/ewolf/3394-96259eb266ae50df8727f64cbd8a64a1_rw/npm-debug.log
nodester npm not ok

nodester warn you should restart your app after you are finished installing packages.
```

**Comment by yocontra** [comment]
Seems like more of an issue with libxmljs than with nodester, doesn't it?

**Comment by yocontra** [comment]
Went ahead and installed it anyways, it isn't a typical dependency for an npm package but I guess some people use funky build processes we should support. Let me know if it works now

**Comment by eflorico** [comment]
Hey, sorry for the late reply. Unfortunately it's still not working, though the error has changed:

```
Eric-Wolfs-MacBook-Pro:updatified ewolf$ nodester npm install libxmljs
nodester info installing to app: updatified
nodester info installing these npm packages: libxmljs
nodester > libxmljs@0.4.2 preuninstall /node/app/ewolf/3394-96259eb266ae50df8727f64cbd8a64a1_rw/node_modules/libxmljs
nodester > make clean
nodester scons: Reading SConscript files ...
nodester > libxmljs@0.4.2 preuninstall /node/app/ewolf/3394-96259eb266ae50df8727f64cbd8a64a1_rw/node_modules/libxmljs
nodester > make clean
nodester scons: Reading SConscript files ...
nodester OSError: [Errno 2] No such file or directory:
nodester   File "/node/app/ewolf/3394-96259eb266ae50df8727f64cbd8a64a1_rw/node_modules/libxmljs/SConstruct", line 43:
nodester     cflags = shellOut([xml2config, '--cflags'])
nodester   File "/node/app/ewolf/3394-96259eb266ae50df8727f64cbd8a64a1_rw/node_modules/libxmljs/SConstruct", line 19:
nodester     return subprocess.Popen(target, stdout=subprocess.PIPE).communicate()[0].strip()
nodester   File "/usr/lib64/python2.6/subprocess.py", line 639:
nodester     errread, errwrite)
nodester   File "/usr/lib64/python2.6/subprocess.py", line 1220:
nodester     raise child_exception
nodester make: *** [clean] Error 2
nodester npm ERR! error installing libxmljs@0.4.2 Error: libxmljs@0.4.2 preuninstall: `make clean`
nodester npm ERR! error installing libxmljs@0.4.2 `sh "-c" "make clean"` failed with 2
nodester npm ERR! error installing libxmljs@0.4.2     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
nodester npm ERR! error installing libxmljs@0.4.2     at ChildProcess.emit (events.js:67:17)
nodester npm ERR! error installing libxmljs@0.4.2     at ChildProcess.onexit (child_process.js:192:12)
nodester OSError: [Errno 2] No such file or directory:
nodester   File "/node/app/ewolf/3394-96259eb266ae50df8727f64cbd8a64a1_rw/node_modules/libxmljs/SConstruct", line 43:
nodester     cflags = shellOut([xml2config, '--cflags'])
nodester   File "/node/app/ewolf/3394-96259eb266ae50df8727f64cbd8a64a1_rw/node_modules/libxmljs/SConstruct", line 19:
nodester     return subprocess.Popen(target, stdout=subprocess.PIPE).communicate()[0].strip()
nodester   File "/usr/lib64/python2.6/subprocess.py", line 639:
nodester     errread, errwrite)
nodester   File "/usr/lib64/python2.6/subprocess.py", line 1220:
nodester     raise child_exception
nodester make: *** [clean] Error 2
nodester npm ERR! error rolling back libxmljs@0.4.2 Error: libxmljs@0.4.2 preuninstall: `make clean`
nodester npm ERR! error rolling back libxmljs@0.4.2 `sh "-c" "make clean"` failed with 2
nodester npm ERR! error rolling back libxmljs@0.4.2     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
nodester npm ERR! error rolling back libxmljs@0.4.2     at ChildProcess.emit (events.js:67:17)
nodester npm ERR! error rolling back libxmljs@0.4.2     at ChildProcess.onexit (child_process.js:192:12)
nodester npm ERR! libxmljs@0.4.2 preuninstall: `make clean`
nodester npm ERR! `sh "-c" "make clean"` failed with 2
nodester npm ERR! 
nodester npm ERR! Failed at the libxmljs@0.4.2 preuninstall script.
nodester npm ERR! This is most likely a problem with the libxmljs package,
nodester npm ERR! not with npm itself.
nodester npm ERR! Tell the author that this fails on your system:
nodester npm ERR!     make clean
nodester npm ERR! You can get their info via:
nodester npm ERR!     npm owner ls libxmljs
nodester npm ERR! There is likely additional logging output above.
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.11-83.9.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "libxmljs"
nodester npm ERR! cwd /node/app/ewolf/3394-96259eb266ae50df8727f64cbd8a64a1_rw
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.18
nodester npm ERR! 
nodester npm ERR! Additional logging details can be found in:
nodester npm ERR!     /node/app/ewolf/3394-96259eb266ae50df8727f64cbd8a64a1_rw/npm-debug.log
nodester npm not ok

nodester warn you should restart your app after you are finished installing packages.
```

This problems seems to have been experienced before - the author replies as follows [here](https://github.com/polotek/libxmljs/issues/34#issuecomment-1311738):

> The xml2-config utility comes with libxml2. The libxmljs build script uses it to get compile flags and include dirs. It needs to be in your path when you run make. Also try npm --loglevel error ... to cut down on the cruft output and see which part of the output is actually relevant. If this doesn't fix it, please open a new ticket with more specific and helpful info including your OS, node, npm and libxmljs versions. Thanks

I hope this can help you in fixing the problem...

**Comment by yocontra** [comment]
I never installed the dependencies (we ran out of disk space)
Once chris gets us over to some new hardware I'll hop on and install them

**Comment by eflorico** [comment]
Alright thanks a lot.. notify me when you're done :)

**Comment by yocontra** [comment]
Depdencies have been installed already, it seems like the issue is with dependencies not being installed on the sandbox

In the time being you can always use an xml library that doesn't have a ton of really weird system dependencies while we work it out. Reopening this and changing the issue title

**Comment by eflorico** [comment]
> In the time being you can always use an xml library that doesn't have a ton of really weird system dependencies while we work it out.

That is actually not as easy as it sounds. I worked through the [list of XML parsers for node.js](https://github.com/joyent/node/wiki/modules#wiki-parsers-xml) and tried out libxmljs (as mentioned above), node-o3-xml and node-xml2json. All others either depend on those I tried, are dependencies of those I tried or do not offer functions to extract the information I need in a sufficiently simple way. The result:

## node-xml2json:

_Error while launching app on Nodester_

```
Error: libexpat.so.1: cannot open shared object file: No such file or directory
    at Object..node (module.js:414:11)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)
    at Object.<anonymous> (/node_modules/node-expat/lib/node-expat.js:3:13)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)
```

## node-o3-xml:

_Fails completely, gives me a segfault when launching node locally_

## libxmljs:

_Error while installing library on Nodester_

```
Eric-Wolfs-MacBook-Pro:updatified ewolf$ nodester npm install libxmljs
[...]
nodester scons: Reading SConscript files ...
nodester OSError: [Errno 2] No such file or directory:
nodester   File "/node/app/ewolf/3394-96259eb266ae50df8727f64cbd8a64a1_rw/node_modules/libxmljs/SConstruct", line 43:
nodester     cflags = shellOut([xml2config, '--cflags'])
nodester   File "/node/app/ewolf/3394-96259eb266ae50df8727f64cbd8a64a1_rw/node_modules/libxmljs/SConstruct", line 19:
nodester     return subprocess.Popen(target, stdout=subprocess.PIPE).communicate()[0].strip()
nodester   File "/usr/lib64/python2.6/subprocess.py", line 639:
nodester     errread, errwrite)
nodester   File "/usr/lib64/python2.6/subprocess.py", line 1220:
nodester     raise child_exception
nodester make: *** [clean] Error 2
nodester npm WARN continuing anyway libxmljs@0.4.2 preuninstall: `make clean`
nodester npm WARN continuing anyway `sh "-c" "make clean"` failed with 2
```

**Comment by yocontra** [comment]
This feature isn't available with our current sandboxing system. You'll have to wait until V2 when we switch to LXC containers. Sorry for the inconvenience!
