### ISSUE TITLE
express failed to located template files

### ISSUE THREAD

**Issue by syshen** [nodester/nodester#196]
My app works fine locally with express with ejs template files under "views" folder. But when I push everything to nodester, app is launched successfully, but I always got "Internal server error" when I accessed the page, and the below error when I query app log:

Error: failed to locate view "root.ejs"
    at Function.compile (/node_modules/express/lib/view.js:58:15)
    at ServerResponse._render (/node_modules/express/lib/view.js:416:18)
    at ServerResponse.render (/node_modules/express/lib/view.js:317:17)
    at Router.handlerRoot (/app/server.js:10:6)
    at done (/node_modules/express/lib/router/index.js:250:22)
    at middleware (/node_modules/express/lib/router/index.js:244:9)
    at param (/node_modules/express/lib/router/index.js:227:11)
    at pass (/node_modules/express/lib/router/index.js:232:6)
    at Router._dispatch (/node_modules/express/lib/router/index.js:255:4)
    at Object.handle (/node_modules/express/lib/router/index.js:45:10)

Is that something related to express version in nodester? 
My app is oauthdemo.nodester.com

**Comment by yocontra** [comment]
Can you paste your code that is loading "root.ejs"?

**Comment by syshen** [comment]
Ah, I found the problem. If I assign the "views" setting in express, then it can locate my template files:

var expressApp = express.createServer();
expressApp.set('views', __dirname + '/views');
console.log('view path = ' + expressApp.set('views'));
expressApp.set('view engine', 'ejs');
