### ISSUE TITLE
Node-canvas modules installed, but gives error when I run my app

### ISSUE THREAD

**Issue by thomasmarshall** [nodester/nodester#226]
I installed the [node-canvas module](https://github.com/LearnBoost/node-canvas) but when I try and run my app I get this error:

```
New PID: 511
chroot_runner
chroot_runner
{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'libcairo.so.2: cannot open shared object file: No such file or directory' }

Error: libcairo.so.2: cannot open shared object file: No such file or directory
    at Object..node (module.js:414:11)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)
    at Object.<anonymous> (/node_modules/canvas/lib/canvas.js:12:14)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)
```

**Comment by yocontra** [comment]
Ah I need to re-install libcairo. Quick fix, should be done by tomorrow. Thanks for reporting it! I can name a few apps that also use node-canvas and are probably having issues now

**Comment by yocontra** [comment]
cairo-devel.x86_64 1.8.8-3.1.4 has been installed. Let me know if you still have any issues!

**Comment by MatthiasWinzeler** [comment]
I'm experiencing the same problem:

```
$ nodester npm install canvas
The "sys" module is now called "util". It should have a similar interface.
nodester info installing to app: everybodydraws
nodester info installing these npm packages: canvas
nodester > canvas@0.8.1 preinstall /node/app/mwinzeler/4371-59f898309406352b3691b76ff23c80c7_rw/node_modules/canvas
nodester > node-waf configure build
nodester canvas@0.8.1 ./node_modules/canvas 
nodester Checking for program g++ or c++          : /usr/bin/g++ 
nodester Checking for program cpp                 : /usr/bin/cpp 
nodester Checking for program ar                  : /usr/bin/ar 
nodester Checking for program ranlib              : /usr/bin/ranlib 
nodester Checking for g++                         : ok  
nodester Checking for node path                   : not found 
nodester Checking for node prefix                 : ok /usr 
nodester Checking for library gif                 : not found 
nodester Checking for library jpeg                : not found 
nodester Checking for cairo                       : yes 
nodester 'configure' finished successfully (0.139s)
nodester Waf: Entering directory `/node/app/mwinzeler/4371-59f898309406352b3691b76ff23c80c7_rw/node_modules/canvas/build'
nodester [1/9] cxx: src/Image.cc -> build/default/src/Image_1.o
nodester [2/9] cxx: src/CanvasRenderingContext2d.cc -> build/default/src/CanvasRenderingContext2d_1.o
nodester [3/9] cxx: src/PixelArray.cc -> build/default/src/PixelArray_1.o
nodester [4/9] cxx: src/color.cc -> build/default/src/color_1.o
nodester [5/9] cxx: src/Canvas.cc -> build/default/src/Canvas_1.o
nodester [6/9] cxx: src/ImageData.cc -> build/default/src/ImageData_1.o
nodester [7/9] cxx: src/init.cc -> build/default/src/init_1.o
nodester [8/9] cxx: src/CanvasGradient.cc -> build/default/src/CanvasGradient_1.o
nodester [9/9] cxx_link: build/default/src/Image_1.o build/default/src/CanvasRenderingContext2d_1.o build/default/src/PixelArray_1.o build/default/src/color_1.o build/default/src/Canvas_1.o build/default/src/ImageData_1.o build/default/src/init_1.o build/default/src/CanvasGradient_1.o -> build/default/canvas.node
nodester Waf: Leaving directory `/node/app/mwinzeler/4371-59f898309406352b3691b76ff23c80c7_rw/node_modules/canvas/build'
nodester 'build' finished successfully (1.800s)

nodester warn you should restart your app after you are finished installing packages.

$ nodester app restart
The "sys" module is now called "util". It should have a similar interface.
nodester info Attemping to restart app: everybodydraws
nodester info app restarted.

$ nodester app logs
The "sys" module is now called "util". It should have a similar interface.
nodester info Showing logs for: everybodydraws
New PID: 12738
chroot_runner
chroot_runner


node.js:134

        throw e; // process.nextTick error, or 'error' event on first tick



^

Error: libcairo.so.2: cannot open shared object file: No such file or directory
    at Object..node (module.js:414:11)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)
    at Object.<anonymous> (/node_modules/canvas/lib/bindings.js:7:20)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)

Process died with exit code 1. Restarting...
```

Strange behaviour - `node-waf configure build` (which in turn uses pkgconfig to determine the libs) finds it on compile time but it is not found on runtime...

**Comment by yocontra** [comment]
This feature isn't available to free users until V2 comes out (soon!).

**Comment by gerrytsui** [comment]
I want to chime in as I am waiting for node-canvas module (native libcairo) support
