### ISSUE TITLE
Can not create nodester acount

### ISSUE THREAD

**Issue by giobero** [nodester/nodester#234]
I've asked this on <a href="http://stackoverflow.com/questions/8226280/can-not-create-nodester-acoount">stackoveflow</a> too.

I want to register on http://nodester.com/. I got my coupon, registered on site, installed nodester (npm install nodester-cli -g)

and user setup command (nodester user setup gio.beri@gmail.com pass***) gives me error:

nodester info verifying credentials

<pre>
/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/vendor/cookie/index.js:45
    : url.parse(req.url).pathname;
                   ^
TypeError: Cannot read property 'url' of undefined
    at new Cookie (/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/vendor/cookie/index.js:45:20)
    at /usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:432:33
    at Array.forEach (native)
    at Request. (/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:426:46)
    at Request.emit (events.js:64:17)
    at IncomingMessage. (/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:391:16)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at CleartextStream.ondata (http.js:1231:22)
    at CleartextStream._push (tls.js:303:27)

</pre>

I'm running on Ubuntu 11.04, tried on nodejs v.0.4.11 and v.0.6.11 but the same error.

**Comment by giobero** [comment]
I think problem is in my password. what must me written there? coupon???

**Comment by yocontra** [comment]
The syntax is `nodester user setup <username> <password>`

Putting an @ in your username is messing up the library we use to parse URLs
