### ISSUE TITLE
App delete hangs

### ISSUE THREAD

**Issue by yocontra** [nodester/nodester#247]
In progress.

**Comment by rnrodrigues** [comment]
No more needs to delete. My apps are working fine now. Thanks for all.

**Comment by sadasant** [comment]
I need to delete my app, when I **commit** it says:

``` bash
remote: Syncing repo with chroot
remote: U   server.js
remote: Pull is not possible because you have unmerged files.
remote: Please, fix them up in the work tree, and then use 'git add/rm <file>'
remote: as appropriate to mark resolution, or use 'git commit -a'.
remote: Attempting to restart your app: 4840-1e0aecbe7840441c4324693765320b78
remote: {"status":"restarted"}
remote: App restarted..
remote: 
remote:   \m/ Nodester out \m/
remote: 
To git@nodester.com:/node/git/sadasant/4840-1e0aecbe7840441c4324693765320b78.git
   83f35d4..4a3b6f9  master -> master
```

I tired to **force push** and I get the same, when I try to gitreset my app it says:

``` bash
nodester ERROR [HTTP 500] <html><head><title id="title">500 - Application error</title></head><body><br/><br/><br/><br/><br/><center><img src="http://nodester.com/images/rocket-down.png" alt="logo" /><br/><h1 style ="color:#000;font-family:Arial,Helvetica,sans-serif;font-size:38px;font-weight:bold;letter-spacing:-2px;padding:0 0 5px;margin:0;">503</h1><h3 style ="color:#000;font-family:Arial,Helvetica,sans-serif;font-size:24px;font-weight:bold;padding:0 0 5px;margin:0;">Application error</h3></center></body></html>
```

If I try to **remove** the app:

``` bash
[dan@sadasant nodester]$ nodester app delete bledge
nodester warn deleting app: bledge
nodester warn Are you sure you want to do this?
     Waiting 10 seconds before continuing, Ctrl+C to abort)
...........
nodester warn Really deleting app now, you were warned..
nodester ERROR [HTTP 500] <html><head><title id="title">500 - Application error</title></head><body><br/><br/><br/><br/><br/><center><img src="http://nodester.com/images/rocket-down.png" alt="logo" /><br/><h1 style ="color:#000;font-family:Arial,Helvetica,sans-serif;font-size:38px;font-weight:bold;letter-spacing:-2px;padding:0 0 5px;margin:0;">503</h1><h3 style ="color:#000;font-family:Arial,Helvetica,sans-serif;font-size:24px;font-weight:bold;padding:0 0 5px;margin:0;">Application error</h3></center></body></html>
```

If I try to **create** my app again:

``` bash
[dan@sadasant nodester]$ nodester app create bledge
nodester info creating app: bledge server.js
nodester ERROR failure
```

And **init**ializing my app again:

``` bash
[dan@sadasant nodester]$ nodester app init bledge
nodester info initializing git repo for bledge into folder bledge
nodester info cloning the repo git clone git@nodester.com:/node/git/sadasant/4840-1e0aecbe7840441c4324693765320b78.git bledge
Enter passphrase for key '/home/dan/.ssh/id_rsa': 
nodester info clone complete
nodester info Writing app data to config in bledge/.nodester.appconfig
nodester info writing app files
nodester info processing the initial commit
Enter passphrase for key '/home/dan/.ssh/id_rsa': 
nodester info attemping to start the new app.
nodester ERROR [HTTP 408] failure - application already running.
```

The **info** says:

``` bash
nodester info Gathering information about: bledge
nodester info bledge on port 12993 running: true (pid: 27277)
nodester info gitrepo: git@nodester.com:/node/git/sadasant/4840-1e0aecbe7840441c4324693765320b78.git
nodester info appfile: server.js
```

The **logs** say many times:

``` bash
/app/server.js:1

<<<<<<< HEAD

^^



node.js:134

        throw e; // process.nextTick error, or 'error' event on first tick


 ^

SyntaxError: Unexpected token <<
    at Module._compile (module.js:397:25)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at Array.<anonymous> (module.js:421:10)
    at EventEmitter._tickCallback (node.js:126:26)

Error: Restarted too many times, bailing.
```

So it's a git broken merge or something like, I wish to delete it in order to start again, but as I said, I can't.

Many thanks and congratulations for your hard work on this platform.

**Comment by yocontra** [comment]
@sadasant - 

```
git add . -A
git commit -m 'merge'
git push origin master
```

If that doesn't work stop the app, init it, and push again. Force pushes aren't available on our server

**Comment by sadasant** [comment]
I tried both but they didn't work... I also tried to stop before deleting, and then init it again without work. I tried stopping and deleting it, then the info says it exists but it stopped, so I cloned it, the files were clean, I pulled, it was up to date, I edited the files then commited and pushed, and the error of the unmerged files appeared...

**Comment by yocontra** [comment]
I'll look into it

**Comment by sadasant** [comment]
Thanks!

**Comment by rnrodrigues** [comment]
It's true. There is any problem with delete via api and nodester-cli. I created another application and I try to delete it. I had the same response error of sadasant.

**Comment by diorahman** [comment]
I could see, it is still in progress :-) Go nodester!

**Comment by chrismatthieu** [comment]
I fixed the API and updated the docs.  The issue was with passing params via the DELETE verb. Apparently the params need to be included in the URL like this:

curl -X DELETE -u "testuser:123" http://api.nodester.com/app/appname

**Comment by chrismatthieu** [comment]
I opened the following ticket to update the CLI with the new REST API changes.

https://github.com/nodester/nodester-cli/issues/33

**Comment by sadasant** [comment]
Thanks @chrismatthieu :)

**Comment by yocontra** [comment]
Fixed in the latest CLI. Reinstall for the changes to take effect

**Comment by sadasant** [comment]
Thanks a lot @Contra :)
