### ISSUE TITLE
Cannot find module './build/Release/bcrypt_lib', install mongoose-auth failed

### ISSUE THREAD

**Issue by rogerz** [nodester/nodester#264]
I'm trying to install mongoose-auth with `nodester install mongoose-auth` when the app fails to start. 

And I got the following error in logs

```
Error: Cannot find module './build/Release/bcrypt_lib'
    at Function._resolveFilename (module.js:317:11)
    at Function._load (module.js:262:25)
    at require (module.js:346:19)
    at Object.<anonymous> (/node_modules/mongoose-auth/node_modules/bcrypt/bcrypt.js:5:18)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)
    at Object.<anonymous> (/node_modules/mongoose-auth/lib/modules/password/plugin.js:26:14)

Error: Restarted too many times, bailing.
```

While the installation log shows everything is OK

```
rogerz@colinux:cc (master)$ nodester npm install mongoose-auth
The "sys" module is now called "util". It should have a similar interface.
nodester info installing to app: cc
nodester info installing these npm packages: mongoose-auth
nodester > bcrypt@0.4.1 install /node/app/rogerz/4950-1b46e30a23a36bbb9d4e5a224ea670cd_rw/node_modules/mongoose-auth/node_modules/bcrypt
nodester > make build
nodester rm -f bcrypt_lib.node
nodester rm -Rf build
nodester node-waf configure
nodester node-waf build
nodester mongoose-auth@0.0.11 ./node_modules/mongoose-auth
nodester ├── mongoose-types@1.0.3
nodester ├── everyauth@0.2.28 (request@2.9.3 openid@0.3.2 oauth@0.9.5 restler@0.2.4 connect@1.8.5 xml2js@0.1.13)
nodester └── bcrypt@0.4.1
nodester Checking for program g++ or c++          : /usr/bin/g++
nodester Checking for program cpp                 : /usr/bin/cpp
nodester Checking for program ar                  : /usr/bin/ar
nodester Checking for program ranlib              : /usr/bin/ranlib
nodester Checking for g++                         : ok
nodester Checking for program gcc or cc           : /usr/bin/gcc
nodester Checking for gcc                         : ok
nodester Checking for node path                   : not found
nodester Checking for node prefix                 : ok /usr
nodester Checking for function RAND_bytes         : yes
nodester 'configure' finished successfully (0.337s)
nodester Waf: Entering directory `/node/app/rogerz/4950-1b46e30a23a36bbb9d4e5a224ea670cd_rw/node_modules/mongoose-auth/node_modules/bcrypt/build'
nodester [1/4] cxx: src/blowfish.cc -> build/default/src/blowfish_1.o
nodester [2/4] cxx: src/bcrypt.cc -> build/default/src/bcrypt_1.o
nodester [3/4] cxx: src/bcrypt_node.cc -> build/default/src/bcrypt_node_1.o
nodester [4/4] cxx_link: build/default/src/blowfish_1.o build/default/src/bcrypt_1.o build/default/src/bcrypt_node_1.o -> build/default/bcrypt_lib.node
nodester Waf: Leaving directory `/node/app/rogerz/4950-1b46e30a23a36bbb9d4e5a224ea670cd_rw/node_modules/mongoose-auth/node_modules/bcrypt/build'
nodester 'build' finished successfully (1.682s)
```

**Comment by yocontra** [comment]
Strange... it looks like it built into /build/default/ instead of /build/Release. I'll take a look at it later tonight

**Comment by suneel0101** [comment]
Yeah, I'm having the same exact issue.

**Comment by yocontra** [comment]
You might want to post this as an issue with the library creators. It seems their build script is messing up and building into ./build/default when the code is being required from ./build/Release.

**Comment by rogerz** [comment]
Well, the local installation is Okay. 

Nodester seems to have deployed an old version of bcrypt (0.4.1), while locally it is bcrypt (0.5.0).

**Comment by yocontra** [comment]
Try specifically installing 0.5.0 `nodester npm install bcrypt@0.5.0`

**Comment by rogerz** [comment]
Install fails. 
nodester is using a different version of node.js (0.4.9)  than my local machine (0.6.7). 

```
nodester info installing to app: cc
nodester info installing these npm packages: bcrypt@0.5.0
nodester npm ERR! Unsupported
nodester npm ERR! Not compatible with your version of node/npm: bcrypt@0.5.0
nodester npm ERR! Required: {"node":">= 0.6.0"}
nodester npm ERR! Actual:   {"npm":"1.0.106","node":"0.4.9"}
nodester npm ERR!
nodester npm ERR! System Linux 2.6.35.14-106.49.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "bcrypt@0.5.0"
nodester npm ERR! cwd /node/app/rogerz/4950-1b46e30a23a36bbb9d4e5a224ea670cd_rw
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.106
nodester npm ERR! code ENOTSUP
nodester npm ERR!
nodester npm ERR! Additional logging details can be found in:
nodester npm ERR!     /node/app/rogerz/4950-1b46e30a23a36bbb9d4e5a224ea670cd_rw/npm-debug.log
nodester npm not ok
```

**Comment by yocontra** [comment]
Ah this makes sense then. We don't have any plans to support > 0.4.9 until V2 where you can specify your own version. You should change your code to run on 0.4.9 for the time being
