### ISSUE TITLE
Just updated my node version, now nodester didnt work

### ISSUE THREAD

**Issue by aluksidadi** [nodester/nodester#267]
I just updated my node to 0.7 and now i get this error when running nodester on my command line:

$ nodester app create luksidadi.tutorial2

node.js:216
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: The "sys" module is now called "util".
    at sys.js:1:69
    at NativeModule.compile (node.js:555:5)
    at Function.require (node.js:523:18)
    at Function._load (module.js:298:25)
    at Module.require (module.js:359:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodester-cli/lib/user.js:3:9)
    at Module._compile (module.js:434:26)
    at Object..js (module.js:452:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:310:12)

Any idea?

**Comment by yocontra** [comment]
Open this in the nodester-cli repository. I think you mean 0.6.7 too

**Comment by aluksidadi** [comment]
i fixed this problem by editing this file:
/nodester-cli/lib/user.js

changed 
sys = require('sys') to sys = require('util')
