### ISSUE TITLE
nodester seems to be down

### ISSUE THREAD

**Issue by nkhine** [nodester/nodester#302]
hi,
it seems the nodester server seems to be down again.

**Comment by chrismatthieu** [comment]
We restarted the proxy and it came back.  We are looking into this issue:

tail -F /node/logs/proxy.log
   at net.js:724:19
   at Object.lookup (dns.js:153:45)
   at Socket.connect (net.js:718:20)
   at Object.createConnection (net.js:265:5)
   at /node/nodester/nodester/node_modules/bouncy/lib/parse_args.js:35:31
   at /node/nodester/nodester/node_modules/bouncy/index.js:69:20
   at /node/nodester/nodester/proxy/proxy.js:62:18
   at IncomingMessage.onHeaders (/node/nodester/nodester/node_modules/bouncy/index.js:52:13)
   at IncomingMessage.emit (events.js:64:17)
   at Parser.<anonymous> (/node/nodester/nodester/node_modules/bouncy/node_modules/parsley/lib/modes.js:135:21)
