### ISSUE TITLE
jsdom 0.2.12 and node 0.4.9

### ISSUE THREAD

**Issue by albertosantini** [nodester/nodester#317]
With jsdom 0.2.12, jquery 1.6.3 and node 0.4.9

TypeError: Cannot set property style of #<error> which has only a getter
    at Object.Node (/node_modules/trammi/node_modules/jquery/node_modules/jsdom/lib/jsdom/level1/core.js:348:14)
    at Object.Element (/node_modules/trammi/node_modules/jquery/node_modules/jsdom/lib/jsdom/level1/core.js:970:13)
    at Object.<anonymous> (/node_modules/trammi/node_modules/jquery/node_modules/jsdom/lib/jsdom/level2/html.js:155:17)
    at Object.<anonymous> (/node_modules/trammi/node_modules/jquery/node_modules/jsdom/lib/jsdom/level2/html.js:155:17)
    at /node_modules/trammi/node_modules/jquery/node_modules/jsdom/lib/jsdom/level2/html.js:203:16
    at Object.createElement (/node_modules/trammi/node_modules/jquery/node_modules/jsdom/lib/jsdom/level1/core.js:1215:75)
    at /node_modules/trammi/node_modules/jquery/node-jquery.js:1175:21
    at /node_modules/trammi/node_modules/jquery/node-jquery.js:1423:2
    at create (/node_modules/trammi/node_modules/jquery/node-jquery.js:9059:2)
    at /node_modules/trammi/node_modules/jquery/node-jquery.js:9065:18

Locally with node 0.6.x it works fine.

The workaround is to load jsdom 0.2.10. 
Maybe it works also jsdom 0.2.11, but I didn't test it.

**Comment by alejandro** [comment]
Hi @albertosantini what I think is that maybe `jsdom` doesn't play well with the `0.4.x` version. The same for the other issue. We are working hard to provide multiple versions of node, soon as posible, so stay tuned :)

**Comment by albertosantini** [comment]
I saw the commits about "n". 

I reported the problem with the workaround just in case someone updates jsdom to the latest version.

Thanks for your efforts.

**Comment by alejandro** [comment]
Elijah Insua (@tmpvar) just tweeted about a bug fixed for jsdom@0.2.13 for 0.4.x versions, you may want to take a look.

RF. [https://twitter.com/#!/tmpvar/status/174309250313629696](https://twitter.com/#!/tmpvar/status/174309250313629696)

**Comment by tmpvar** [comment]
This is the exact bug that was fixed in the latest jsdom release.  Please let me know if things are still broken

**Comment by albertosantini** [comment]
@tmpvar Thanks for the fix - jsdom@0.2.13. It works nice on nodester (node 0.4.9).
