### ISSUE TITLE
nodester app setup doesn't work

### ISSUE THREAD

**Issue by rmetzler** [nodester/nodester#342]
```
    $ nodester app setup
    nodester ERROR appname required
    $ nodester app setup test

    node.js:201
            throw e; // process.nextTick error, or 'error' event on first tick
                  ^
    Error: ENOENT, no such file or directory ''
        at Object.mkdirSync (fs.js:373:18)
        at Object.writeApp (/usr/local/lib/node_modules/nodester-cli/lib/config.js:53:5)
        at Object.setup (/usr/local/lib/node_modules/nodester-cli/lib/app.js:26:12)
        at Object.run (/usr/local/lib/node_modules/nodester-cli/lib/commands.js:100:51)
        at Object.<anonymous> (/usr/local/lib/node_modules/nodester-cli/bin/nodester.js:12:5)
        at Module._compile (module.js:432:26)
        at Object..js (module.js:450:10)
        at Module.load (module.js:351:31)
        at Function._load (module.js:310:12)
        at Array.0 (module.js:470:10)
    rmetzler-macbook:nodester(master) richard$ 
```

**Comment by rmetzler** [comment]
the description also suggest to rename `setup` to `config`

**Comment by alejandro** [comment]
What are you trying to do? the setup command is for repos that already exists in your local machine.

**Comment by rmetzler** [comment]
ok, then it would be nice when the response would be: "repo doesn't exist"

I'm sorry, I didn't read any tutorials about nodester. I'm not sure if I should follow the "happy path" or report what I find confusing about nodester. I just think it should never throw exceptions that don't explain what went wrong.

**Comment by alejandro** [comment]
@rmetzler yeah you are right! I'll take care of it! you may want to read http://nodester.com/api.html for further reference...
