### ISSUE TITLE
Issues with 'app init' under Ubuntu (Bad file descriptor)

### ISSUE THREAD

**Issue by cjoudrey** [nodester/nodester#36]
This might be a problem on my end, but there seems to be a problem with 'app init'. It's failing to create the folder.

```
cjoudrey@duo:~/Web$ nodester app init mynodesterapp3 ./mynodesterapp3

fs.js:184
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: EBADF, Bad file descriptor './mynodesterapp3/.nodester.appconfig'
    at Object.openSync (fs.js:184:18)
    at Object.writeFileSync (fs.js:436:15)
    at /usr/local/lib/node/.npm/nodester-cli/0.1.7/package/bin/nodester.js:274:16
    at ChildProcess.exithandler (child_process.js:85:7)
    at ChildProcess.emit (events.js:45:17)
    at ChildProcess.onexit (child_process.js:171:12)
```

I tried creating the folder manually, but it still crashes at the same spot with an extra error message 'file exists'.

**Comment by cjoudrey** [comment]
Moved to nodester-cli
