### ISSUE TITLE
Unable to install npm modules depending on node version > v0.4.9

### ISSUE THREAD

**Issue by eflorico** [nodester/nodester#362]
I have upgraded my app to node v0.6.12:

```
New PID: 4772
chroot_runner
chroot_runner
Running node v-0.6.12
```

Yet when I try to install mongoskin, which apparently depends on node v0.4.12, I get this error:

```
nodester info installing to app: updatified
nodester info installing these npm packages: mongoskin
nodester npm ERR! error installing mongodb@0.9.9-7 Error: Unsupported
nodester npm ERR! error installing mongodb@0.9.9-7     at checkEngine (/usr/lib/node_modules/npm/lib/install.js:493:14)
nodester npm ERR! error installing mongodb@0.9.9-7     at Array.0 (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
nodester npm ERR! error installing mongodb@0.9.9-7     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:13)
nodester npm ERR! error installing mongodb@0.9.9-7     at chain (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:4)
nodester npm ERR! error installing mongodb@0.9.9-7     at installOne_ (/usr/lib/node_modules/npm/lib/install.js:470:3)
nodester npm ERR! error installing mongodb@0.9.9-7     at installOne (/usr/lib/node_modules/npm/lib/install.js:411:3)
nodester npm ERR! error installing mongodb@0.9.9-7     at /usr/lib/node_modules/npm/lib/install.js:347:9
nodester npm ERR! error installing mongodb@0.9.9-7     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:54:35
nodester npm ERR! error installing mongodb@0.9.9-7     at Array.forEach (native)
nodester npm ERR! error installing mongodb@0.9.9-7     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:54:11
nodester npm ERR! error installing mongoskin@0.3.4 Error: Unsupported
nodester npm ERR! error installing mongoskin@0.3.4     at checkEngine (/usr/lib/node_modules/npm/lib/install.js:493:14)
nodester npm ERR! error installing mongoskin@0.3.4     at Array.0 (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
nodester npm ERR! error installing mongoskin@0.3.4     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:13)
nodester npm ERR! error installing mongoskin@0.3.4     at chain (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:4)
nodester npm ERR! error installing mongoskin@0.3.4     at installOne_ (/usr/lib/node_modules/npm/lib/install.js:470:3)
nodester npm ERR! error installing mongoskin@0.3.4     at installOne (/usr/lib/node_modules/npm/lib/install.js:411:3)
nodester npm ERR! error installing mongoskin@0.3.4     at /usr/lib/node_modules/npm/lib/install.js:347:9
nodester npm ERR! error installing mongoskin@0.3.4     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:54:35
nodester npm ERR! error installing mongoskin@0.3.4     at Array.forEach (native)
nodester npm ERR! error installing mongoskin@0.3.4     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:54:11
nodester npm ERR! Unsupported
nodester npm ERR! Not compatible with your version of node/npm: bson@0.0.4
nodester npm ERR! Required: {"node":">=0.4.12"}
nodester npm ERR! Actual:   {"npm":"1.0.106","node":"0.4.9"}
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.53.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "mongoskin"
nodester npm ERR! cwd /node/app/ewolf/5848-2635b42757e49e447d9776e961068b1e_rw
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.106
nodester npm ERR! code ENOTSUP
nodester npm ERR! 
nodester npm ERR! Additional logging details can be found in:
nodester npm ERR!     /node/app/ewolf/5848-2635b42757e49e447d9776e961068b1e_rw/npm-debug.log
nodester npm not ok
```

**Comment by alejandro** [comment]
@elektrowolf can you paste your `package.json` (I know that the version says 0.6.12) But we have found that sometimes this error is because a `v` in your node version.

Cheers.

**Comment by eflorico** [comment]
That was it, thanks! You might want to correct this on the page you linked in the Nodester FAQ: http://blog.nodester.com/post/18702499832/nodester-now-running-node-js-0-6-12

**Comment by alejandro** [comment]
@elektrowolf better i'll fix the code :) 

[8fa862](https://github.com/nodester/nodester/commit/8fa86207bb54c3266cd9e68e89fd5cc4b34a0572)
**Closing this**
