### ISSUE TITLE
Couldn't install package due to "node-gyp rebuild" error

### ISSUE THREAD

**Issue by roskoff** [nodester/nodester#382]
To reproduce the error, try to install jsdom on your nodester app:

```
$ nodester npm install jsdom
nodester info installing to app: onmdata
nodester info installing these npm packages: jsdom
nodester > contextify@0.1.3 install /node/app/eocampos/8901-855c154495fa3405d078dca02f88b7_rw/node_modules/jsdom/node_modules/contextify
nodester > node-gyp rebuild
nodester jsdom@0.2.14 ./node_modules/jsdom
nodester ├── cssom@0.2.3
nodester ├── request@2.9.202
nodester └── htmlparser@1.7.6
nodester npm http GET https://registry.npmjs.org/jsdom
nodester npm http 304 https://registry.npmjs.org/jsdom
nodester npm http GET https://registry.npmjs.org/htmlparser
nodester npm http GET https://registry.npmjs.org/cssom
nodester npm http GET https://registry.npmjs.org/request
nodester npm http GET https://registry.npmjs.org/contextify
nodester npm http 304 https://registry.npmjs.org/request
nodester npm http 304 https://registry.npmjs.org/cssom
nodester npm http 304 https://registry.npmjs.org/htmlparser
nodester npm http 304 https://registry.npmjs.org/contextify
nodester npm http GET https://registry.npmjs.org/bindings
nodester npm http 304 https://registry.npmjs.org/bindings
nodester node.js:134
nodester         throw e; // process.nextTick error, or 'error' event on first tick
nodester         ^
nodester Error: Cannot find module '../package'
nodester     at Function._resolveFilename (module.js:317:11)
nodester     at Function._load (module.js:262:25)
nodester     at require (module.js:346:19)
nodester     at Object.<anonymous> (/node/base/node-v0.4.9/usr/local/n/versions/0.6.17/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:68:17)
nodester     at Module._compile (module.js:402:26)
nodester     at Object..js (module.js:408:10)
nodester     at Module.load (module.js:334:31)
nodester     at Function._load (module.js:293:12)
nodester     at require (module.js:346:19)
nodester     at Object.<anonymous> (/node/base/node-v0.4.9/usr/local/n/versions/0.6.17/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:13:11)
nodester npm WARN optional dependency failed, continuing contextify@0.1.3

nodester warn you should restart your app after you are finished installing packages
```

This tries to install contextify (as a jsdom dependency) and fails with displayed error message.

**Comment by chrismatthieu** [comment]
Did you restart your app after installing your npm modules?
Do you have any native modules in your dependencies?

**Comment by roskoff** [comment]
Now I just tried that and still fails. My app doesn't work because relies on request and jsdom. It seems that when I try to install jsdom via "nodester npm install jsdom" fails for some reason when installing the contextify module. I'm managing to install a local nodester server for proper debug, in the meantime I asked for help here :)

I have to say that jsdom installs correctly in my notebook, with node v0.6.17 and npm v1.1.23

**Comment by alejandro** [comment]
I don't know why contextify is failing on the server. I tried to manually install it and it failed also.

>    :`nodester npm WARN optional dependency failed, continuing contextify@0.1.3`

The interesting part is that this module is an optional one. According to [this](https://github.com/isaacs/npm/issues/995)  `jsdom` should be working. Let me run some test, and I hope we'll found a fix for this.

**Comment by roskoff** [comment]
I see. Maybe when [the installer script](https://github.com/nodester/nodester-installer/issues/8) is finished I will have good chance to walk through this. I already tried it in a "semi-installed-nodester-server" and I had issues with `NODE_PATH` environment variable, I couldn't install the contextify package because of this. I'm not sure that this could be the issue on nodester.com server, since I'm not sure that my installation was completely correct.

**Comment by alejandro** [comment]
Ok we have fixed this problem, it was a server issue:

```
$ nodester npm install harmony jsdom:
nodester info installing these npm packages: jsdom
nodester > contextify@0.1.3 install /node/app/alejandromg/11405-173d54f60756aee1c6f9510d05fbc69a_rw/node_modules/jsdom/node_modules/contextify
nodester > node-gyp rebuild
nodester { http_parser: '1.0',
nodester   node: '0.8.1',
nodester   v8: '3.11.10.12',
nodester   ares: '1.7.5-DEV',
nodester   uv: '0.8',
nodester   zlib: '1.2.3',
nodester   openssl: '1.0.0f' }
nodester make: Entering directory `/node/app/alejandromg/11405-173d54f60756aee1c6f9510d05fbc69a_rw/node_modules/jsdom/node_modules/contextify/build'
nodester   CXX(target) Release/obj.target/contextify/src/contextify.o
nodester   SOLINK_MODULE(target) Release/obj.target/contextify.node
nodester   SOLINK_MODULE(target) Release/obj.target/contextify.node: Finished
nodester   COPY Release/contextify.node
nodester make: Leaving directory `/node/app/alejandromg/11405-173d54f60756aee1c6f9510d05fbc69a_rw/node_modules/jsdom/node_modules/contextify/build'
nodester jsdom@0.2.14 node_modules/jsdom
nodester ├── cssom@0.2.4
nodester ├── request@2.9.203
nodester ├── htmlparser@1.7.6
nodester └── contextify@0.1.3 (bindings@1.0.0)
nodester npm http GET https://registry.npmjs.org/jsdom
nodester npm http 304 https://registry.npmjs.org/jsdom
nodester npm http GET https://registry.npmjs.org/cssom
nodester npm http GET https://registry.npmjs.org/request
nodester npm http GET https://registry.npmjs.org/contextify
nodester npm http GET https://registry.npmjs.org/htmlparser
nodester npm http 304 https://registry.npmjs.org/contextify
nodester npm http 304 https://registry.npmjs.org/cssom
nodester npm http 304 https://registry.npmjs.org/request
nodester npm http 304 https://registry.npmjs.org/htmlparser
nodester npm http GET https://registry.npmjs.org/bindings
nodester npm http 304 https://registry.npmjs.org/bindings
nodester gyp http GET http://nodejs.org/dist/v0.8.1/node-v0.8.1.tar.gz
nodester gyp http 200 http://nodejs.org/dist/v0.8.1/node-v0.8.1.tar.gz

nodester info Dependencies installed
nodester info Attemping to restart app: harmony
nodester info app restarted.
nodester info ok!

```

Closing this :D

/be
