### ISSUE TITLE
Unable to run nodester

### ISSUE THREAD

**Issue by tirithen** [nodester/nodester#417]
I get the following error:

```
crypto.js:332
  this._binding.init(cipher, toBuf(password));
                ^
Error: Must give cipher-type, key as argument
    at new Decipher (crypto.js:332:17)
    at decryptAuth (/usr/lib/node_modules/nodester-cli/lib/config.js:68:14)
    at Object.exports.parse (/usr/lib/node_modules/nodester-cli/lib/config.js:165:13)
    at Object.<anonymous> (/usr/lib/node_modules/nodester-cli/lib/commands.js:58:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

It's probobly related to my node version, I get this error while trying to update npm:

```
npm WARN engine nodester-cli@1.1.1: wanted: {"node":">0.6.x =<0.8.x"} (current: {"node":"v0.10.17","npm":"1.3.9"})
```

**Comment by AR-Student824** [comment]
been years, still open lol
