### ISSUE TITLE
Error while using 'new Buffer()'

### ISSUE THREAD

**Issue by grender** [nodester/nodester#74]
When i try to use Buffer class my app crashed. 

Ther is code
        var http = require('http');

```
    http.createServer(serverMain).listen(8807);
    function serverMain(request, response){
    response.writeHead(200, {
        'Content-Type': 'text/html'
    });
    var t=new Buffer("Hello", 'binary').toString('base64');
    console.log(t);
    response.end(t);
    return;
    }
```

And app log:  
    [INFO] Nodester listening on port: ---- 
    ReferenceError: Buffer is not defined
    at Server.serverMain (test.js:9:3)
    at Server.emit (events.js:45:17)
    at HTTPParser.onIncoming (http.js:1046:12)
    at HTTPParser.onHeadersComplete (http.js:87:31)
    at Socket.ondata (http.js:945:22)
    at Socket._onReadable (net.js:654:27)
    at IOWatcher.onReadable [as callback](net.js:156:10){ stack: [Getter/Setter
    ],
    arguments: [ 'Buffer' ],
    type: 'not_defined',
    message: [Getter/Setter] }

**Comment by davglass** [comment]
Just pushed a fix for this, can you close once confirmed?

**Comment by grender** [comment]
Ok. Thank you. All work fine.
