### ISSUE TITLE
Nodester Stops Accepting Connections with Traffic

### ISSUE THREAD

**Issue by chrismatthieu** [nodester/nodester#91]
Chats.io made the front page of Hacker News today (http://news.ycombinator.com/item?id=2343840) and Nodester couldn't handle the traffic. Connections would timeout and Nodester needed to be constantly restarted to accept connections again.

**Comment by chrismatthieu** [comment]
The problem seems to be in the proxy.js file.  It seems to just stop taking new requests.  Restarting proxy.js solves the issue but I am having to do it every 10-15 minutes :(

**Comment by chrismatthieu** [comment]
I noticed these errors when proxy stopped routing:

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /home/ec2-user/nodester/lib/3rdparty/proxy-table.js:53:32
    at [object Object].<anonymous> (fs.js:86:5)
    at [object Object].emit (events.js:39:17)
    at afterRead (fs.js:840:12)
watchFile
updateRoutes fired
watchFile
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /home/ec2-user/nodester/lib/3rdparty/proxy-table.js:53:32
    at [object Object].<anonymous> (fs.js:86:5)
    at [object Object].emit (events.js:39:17)
    at afterRead (fs.js:840:12)
watchFile
updateRoutes fired

**Comment by marcosvm** [comment]
Chris,

Do you have an idea of the kind of traffic we got, in request/sec?

On Sat, Mar 19, 2011 at 11:11 AM, chrismatthieu
reply@reply.github.com
wrote:

**Comment by chrismatthieu** [comment]
I dont have any data but at one time we had 100 or so people in a chats.io chatroom and it handled it well.  The issue seems to be happening on the frequency of connections perhaps as the issue is still occurring even with only 5 people in the chat room.

**Comment by chrismatthieu** [comment]
here is the latest log from running proxy.js:

Error: Parse Error
    at Client.onData [as ondata](http.js:1380:27)
    at Client._onReadable (net.js:654:27)
    at IOWatcher.onReadable [as callback](net.js:156:10)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
    at Pool.<anonymous> (events.js:101:17)
    at Object.proxyRequest (/home/ec2-user/nodester/lib/3rdparty/node-http-proxy.js:196:7)
    at [object Object].proxyRequest (/home/ec2-user/nodester/lib/3rdparty/proxy-table.js:105:15)
    at Server.<anonymous> (/home/ec2-user/nodester/lib/3rdparty/node-http-proxy.js:95:18)
    at Server.emit (events.js:45:17)
    at HTTPParser.onIncoming (http.js:1046:12)
    at HTTPParser.onHeadersComplete (http.js:87:31)
    at Socket.ondata (http.js:945:22)
    at Socket._onReadable (net.js:654:27)
    at IOWatcher.onReadable [as callback](net.js:156:10)
Error: Parse Error
    at Client.onData [as ondata](http.js:1380:27)
    at Client._onReadable (net.js:654:27)
    at IOWatcher.onReadable [as callback](net.js:156:10)
Error: Parse Error
    at Client.onData [as ondata](http.js:1380:27)
    at Client._onReadable (net.js:654:27)
    at IOWatcher.onReadable [as callback](net.js:156:10)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
    at Pool.<anonymous> (events.js:101:17)
    at Object.proxyRequest (/home/ec2-user/nodester/lib/3rdparty/node-http-proxy.js:196:7)
    at [object Object].proxyRequest (/home/ec2-user/nodester/lib/3rdparty/proxy-table.js:105:15)
    at Server.<anonymous> (/home/ec2-user/nodester/lib/3rdparty/node-http-proxy.js:95:18)
    at Server.emit (events.js:45:17)
    at HTTPParser.onIncoming (http.js:1046:12)
    at HTTPParser.onHeadersComplete (http.js:87:31)
    at Socket.ondata (http.js:945:22)
    at Socket._onReadable (net.js:654:27)
    at IOWatcher.onReadable [as callback](net.js:156:10)

**Comment by chrismatthieu** [comment]
i added a try/catch around the line in question above and I removed an "undefined" entry from the proxy table.  Let's see if this helps...

**Comment by chrismatthieu** [comment]
didn't help.  the error may be a red herring.

**Comment by chrismatthieu** [comment]
Based on discussions with Dav, it sounds like we will need to rework our proxy.js to handle more concurrent websockets.

**Comment by chrismatthieu** [comment]
Could we verify that the cron job is still restarting proxy.js every 15 minutes to help address this issue?  It looks like @Adrusi is also reporting the same problem with his websocket app.

**Comment by gleicon** [comment]
Just to register what I've commented on irc: I've been hitting it with a new app using node.ws.js - from the browser perspective looks like it's not receiving the headers back after the upgrade with websockets. From the app perspective it gets a timeout. I can't tell for sure if it's related because I'm not using a private nodester setup but I'm not filling the eventemitter neither having a lot of traffic. Seems like the connection hangs from the proxy to the app, and the browser dont get any response.

**Comment by yocontra** [comment]
Closed, our new proxy should fix this. node-http-proxy leaked memory like broken pipe
